# config for getting hypernyms distribution of entities

online: True  # online mode or offline mode
num_entities: 200  # number of entities to be generated
cache_dir: data/anno_res/entity_distribution  # cache directory to save annotation.py results
eval_dir: data/eval/entity_distribution  # evaluation results file dir
des_format: simple  # type description format , 'simple' for simple description, 'full' for full description, 'empty' for no description
natural_form: True  # natural_form is used to indicate whether the labels are in natural language form.

dataset: ???  # the dataset cfg. it's need to be set in 'run.py'
data_cfg_paths:
  conll2003: cfgs/dataset/conll2003.yaml  # relative to the 'run.py' file
  ontonotes5: cfgs/dataset/ontonotes5.yaml
  mit_restaurant: cfgs/dataset/mit_restaurant.yaml
  mit_movie: cfgs/dataset/mit_movie.yaml


# dify_cfg:
entity_app:
  name: tool_agent  # app to generate entities, 'intrinsic' (other), 'tool_agent' (agent)
  app_mode: agent
hypernyms_app:
  name: hypernyms_agent  # app to get entities' hypernyms
  app_mode: agent

dify_api:
  base_url: http://localhost/v1
  hypernyms_agent: app-UBKVJ3lOZetjITpb3e1szwwI
  intrinsic: app-IW8uh8lopyvzAWFUeTf7RzK4  # intrinsic entity generation app token
  tool_agent: app-OE8Ejn9NUPovAnZ3O3fUW2oL # tool entity generation app token
